---
# tasks file for nginx_proxy

- name: Установка Nginx
  apt:
    name: "nginx"
    state: present
  when: "'vm_3' in inventory_hostname"

- name: Подмена файла конфинурации
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  when: "'vm_3' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_1
  notify: "Nginx Reloader"

