---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_1: #Имя машины
          ansible_host: 89.169.149.203  #Адрес машины
        vm_2:
          ansible_host: 89.169.150.166
        vm_3:
          ansible_host: 89.169.129.76
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "root"
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    connection_protocol: ssh #тип подключения
    ansible_become: false #Становиться ли другим пользователем после подключения
